# Generated by Django 2.2.12 on 2021-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fanStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Temperature', models.IntegerField()),
                ('Status', models.CharField(max_length=5)),
                ('Date', models.DateTimeField()),
                ('Mode', models.CharField(max_length=10)),
            ],
        ),
    ]
